name: Python CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint Code with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.4"

      - name: Install uv and black
        run: |
          pip install uv
          uv pip install black

      - name: Run black (check formatting)
        run: |
          uv run black . --check --diff

  test:
    name: Run Tests with uv
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.4"

      - name: Install dependencies and pytest using uv
        run: |
          pip install uv
          uv pip install -e .
          uv pip install pytest

      - name: Run pytest with uv
        run: |
          uv run pytest

  deploy:
    name: Deploy FastAPI
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.BACKEND_REPO_PATH }}
            git stash
            git pull origin main
            source venv/bin/activate
            pip install uv
            uv pip install -e .
            sudo systemctl restart backend.service
